/* Dados do roteiro Sardenha 15–20/08 — 4 adultos, 2 crianças (7 e 8), 2 idosos (76) */

const BASE = { lat: 40.3846, lng: 9.7426, name: "Hotel Marina Garden — Marina di Orosei" };

const DAYS = [
  {
    id: "d0",
    date: "15/08",
    weekday: "Sexta",
    title: "Chegada · Cagliari → Orosei",
    color: "#e2725b",
    badge: "Ferragosto",
    summary:
      "Manhã em Cagliari, transfer de ~2h30 até Orosei à tarde. Dia de deslocamento — não empilhe atrações.",
    alerts: [
      {
        level: "warn",
        text: "15/08 é Ferragosto, feriado nacional. Museus, lojas e muitos restaurantes fecham ou abrem só meio período. Praias e estradas lotadas. Reserve almoço e jantar com antecedência.",
      },
      {
        level: "info",
        text: "Vocês estarão em 2 carros. Combine o ponto de encontro em Orosei antes de sair de Cagliari — no trecho de serra da SS131 DCN o sinal cai e um carro perde o outro com facilidade.",
      },
    ],
    stops: [
      {
        id: "cagliari-castello",
        name: "Castello + Bastione Saint Remy",
        lat: 39.2178,
        lng: 9.1145,
        time: "09:00–11:00",
        kind: "cidade",
        desc: "Bairro histórico no alto. Vista da muralha, catedral, ruelas. Terraço do Bastione é a foto da cidade.",
        senior: "Subida íngreme a pé. Use o elevador público do Bastione (Piazza Costituzione) ou os ascensori de Via Santa Croce. De carro dá pra chegar quase no topo pela Viale Buon Cammino.",
        kids: "Curto. 1h30 é o teto antes do tédio.",
        cost: "Grátis (elevadores grátis)",
      },
      {
        id: "cagliari-elefante",
        name: "Torre dell'Elefante",
        lat: 39.2192,
        lng: 9.1108,
        time: "opcional",
        kind: "cidade",
        desc: "Torre pisana de 1307. Vista aberta do alto.",
        senior: "Pular — escadas de madeira íngremes, sem elevador.",
        kids: "Gostam da subida.",
        cost: "~€3",
      },
      {
        id: "cagliari-almoco",
        name: "Almoço em Cagliari (Marina/Villanova)",
        lat: 39.2141,
        lng: 9.1156,
        time: "12:00–13:30",
        kind: "comida",
        desc: "Bairro Marina tem a maior densidade de trattorias. Peça fregola con arselle, culurgiones, malloreddus.",
        senior: "Escolha lugar com mesa interna com ar-condicionado — meio-dia de agosto em Cagliari passa de 35 °C.",
        kids: "Pizza em qualquer lugar do Marina.",
        cost: "€25–35/pessoa",
        book: true,
      },
      {
        id: "barumini",
        name: "Su Nuraxi de Barumini (parada opcional)",
        lat: 39.7053,
        lng: 8.9906,
        time: "15:00–16:30",
        kind: "cultura",
        desc: "Nuraghe UNESCO, o mais importante da ilha. Visita guiada obrigatória, ~1h. Fica ~50 min fora da rota direta.",
        senior: "Terreno irregular, sol aberto, pouca sombra. Às 15h de agosto é castigo. Se for, vá no último horário.",
        kids: "Melhor coisa 'cultural' da viagem pra idade deles — castelo de pedra de verdade.",
        cost: "€15 adulto",
        optional: true,
      },
      {
        id: "orosei-checkin",
        name: "Check-in Hotel Marina Garden",
        lat: 40.3846,
        lng: 9.7426,
        time: "17:00–18:00",
        kind: "base",
        desc: "Base para os 5 dias. Fica em Marina di Orosei, pé na areia.",
        senior: "Peça quartos no térreo ou perto do elevador na reserva.",
        kids: "Piscina antes do jantar resolve a energia acumulada da estrada.",
      },
      {
        id: "marina-orosei",
        name: "Pôr do sol na praia de Marina di Orosei",
        lat: 40.3856,
        lng: 9.744,
        time: "19:30",
        kind: "praia",
        desc: "Areia larga, dunas, pinheiral. Fim de dia sem esforço nenhum, a 3 min do hotel.",
        senior: "Acesso plano.",
        kids: "Areia solta e rasa perto da margem.",
      },
    ],
    drive: [
      { from: "Cagliari", to: "Orosei", km: 195, min: 150, note: "SS131 DCN. Via Barumini/Nuoro fica ~40 min mais longo." },
    ],
  },

  {
    id: "d1",
    date: "16/08",
    weekday: "Sábado",
    title: "Aclimatação · Orosei e praias locais",
    color: "#3fa796",
    summary:
      "Dia leve de propósito. Todo mundo chegou ontem, a semana tem 1 dia de barco e 2 de estrada. Praias a 10–20 min do hotel.",
    alerts: [
      {
        level: "info",
        text: "Bidderosa tem cota diária de carros (~130) e cobra entrada. Reserva online abre com antecedência e esgota em agosto. Se não conseguir, Cala Liberotto e Sos Alinos são vizinhas e livres.",
      },
    ],
    stops: [
      {
        id: "cala-liberotto",
        name: "Cala Liberotto",
        lat: 40.4519,
        lng: 9.781,
        time: "09:30–13:00",
        kind: "praia",
        desc: "Sequência de enseadas de areia branca com rochas graníticas, água rasa e transparente. A praia mais fácil da região.",
        senior: "Estacionamento perto, entrada plana na água, quiosques com banheiro. Melhor praia do roteiro para os 76 anos.",
        kids: "Água rasa por muitos metros e piscinas naturais entre as rochas.",
        cost: "Estacionamento pago em agosto",
      },
      {
        id: "bidderosa",
        name: "Oasi di Bidderosa (opcional, com reserva)",
        lat: 40.4302,
        lng: 9.7856,
        time: "alternativa manhã",
        kind: "praia",
        desc: "Reserva natural com 5 calas dentro de pinheiral. Número de carros limitado por dia — por isso fica vazia mesmo em agosto.",
        senior: "Entra de carro até perto das calas. Confortável.",
        kids: "Sombra de verdade no pinheiral, raro na Sardenha.",
        cost: "~€12/carro + reserva online",
        optional: true,
        book: true,
      },
      {
        id: "orosei-centro",
        name: "Centro histórico de Orosei",
        lat: 40.3789,
        lng: 9.6963,
        time: "18:00–20:00",
        kind: "cidade",
        desc: "Piazza del Popolo, San Giacomo Maggiore, ruelas de calcário. Passeggiata no fim da tarde, gelato.",
        senior: "Centro pequeno e plano. 40 min a pé cobre tudo.",
        kids: "Gelato e praça aberta.",
      },
    ],
    drive: [{ from: "Hotel", to: "Cala Liberotto", km: 12, min: 15 }],
  },

  {
    id: "d2",
    date: "17/08",
    weekday: "Domingo",
    title: "Dia de barco · Golfo di Orosei",
    color: "#2b7fd4",
    badge: "Reservar já",
    summary:
      "O dia principal. Grotta del Bue Marino + Cala Luna + Cala Mariolu de barco saindo de Cala Gonone. Único jeito prático de ver as três.",
    alerts: [
      {
        level: "warn",
        text: "Reserve MOTONAVE (barco grande, 100–250 lugares, com sombra, banheiro e escada larga com corrimão). Não reserve gommone. Comparação completa dos 3 tipos de barco e as 6 perguntas a fazer ao operador estão na seção 'Que barco pegar' no fim desta página.",
      },
      {
        level: "warn",
        text: "Reserve com 3–4 dias de antecedência no mínimo. Meados de agosto lota. Reserva se faz no porto de Cala Gonone ou online pelos consórcios locais.",
      },
      {
        level: "info",
        text: "Com 2 carros há uma saída se os dois de 76 anos não aguentarem 7h de mar: taxi boat de ~20 min entre Cala Gonone e Cala Luna. Eles fazem meio dia e voltam; o resto segue até Cala Mariolu.",
      },
      {
        level: "info",
        text: "Cala Mariolu e Cala Goloritzé têm cota diária de visitantes (costa de Baunei). Os operadores de barco normalmente já incluem o ticket — confirme na hora de reservar.",
      },
    ],
    stops: [
      {
        id: "cala-gonone-porto",
        name: "Porto de Cala Gonone — embarque",
        lat: 40.2833,
        lng: 9.6339,
        time: "08:15 no porto / saída ~09:00",
        kind: "porto",
        desc: "Chegue 45 min antes. Estacionamento no porto enche cedo — em agosto, se estiver cheio, use os estacionamentos da parte alta e desça.",
        senior: "Deixe os dois idosos e a bagagem de praia na entrada do porto antes de estacionar.",
        kids: "Banheiro antes de embarcar — no barco a fila é longa.",
        cost: "€45–60 adulto, meia para crianças (varia por roteiro)",
        book: true,
      },
      {
        id: "bue-marino",
        name: "Grotta del Bue Marino",
        lat: 40.2492,
        lng: 9.6206,
        time: "~09:30, visita 1h",
        kind: "gruta",
        desc: "Caverna marinha, última casa da foca-monge no Mediterrâneo ocidental. Visita guiada por passarela iluminada, estalactites e lago interno. ~900 m de percurso.",
        senior: "Passarela de concreto com corrimão, alguns degraus. Viável nos 76 anos em ritmo próprio. Interior é fresco (~20 °C) — leve uma blusa. Chão fica úmido/escorregadio: calçado fechado com sola, não chinelo.",
        kids: "Escuro e ecoante, com história de foca. Costuma ser o ponto alto pra criança.",
        cost: "Ticket da gruta geralmente à parte, ~€10",
      },
      {
        id: "cala-luna",
        name: "Cala Luna",
        lat: 40.2249,
        lng: 9.6232,
        time: "~11:00, parada 1h30–2h",
        kind: "praia",
        desc: "Praia larga de areia clara sob paredão calcário, com grutas abertas no fundo da enseada. A mais espaçosa do golfo.",
        senior: "A melhor parada do dia para eles: desembarque em areia, praia plana, grutas com sombra a poucos metros. Tem quiosque.",
        kids: "As grutas no fundo da praia são exploráveis a pé.",
      },
      {
        id: "cala-mariolu",
        name: "Cala Mariolu",
        lat: 40.1442,
        lng: 9.6462,
        time: "~13:30, parada 1h30",
        kind: "praia",
        desc: "Seixos brancos arredondados ('piedini') e água em degradê de turquesa. A água mais bonita do golfo.",
        senior: "Atenção: não é areia. Seixo é instável para caminhar e o fundo desce rápido. Se estiver com ondulação, considerem ficar no barco — a vista da enseada já vale.",
        kids: "Fundo cai rápido perto da margem. Boia/colete nas duas crianças.",
        cost: "Sapatilha de neoprene ajuda muito aqui — vale comprar em Cala Gonone antes.",
      },
      {
        id: "cala-gonone-volta",
        name: "Volta a Cala Gonone + jantar",
        lat: 40.2833,
        lng: 9.6339,
        time: "~17:00",
        kind: "comida",
        desc: "Jante no porto de Cala Gonone e volte a Orosei sem pressa, ou volte direto ao hotel. A estrada Cala Gonone–Dorgali é serra com curvas fechadas.",
        senior: "Depois de 8h de barco e sol, o mais provável é que queiram voltar direto. Planeje o jantar simples.",
      },
    ],
    drive: [
      { from: "Hotel", to: "Cala Gonone", km: 34, min: 40, note: "Saia 07:15. Estrada de montanha com túnel; não é rápida." },
    ],
    pack: ["Protetor solar (o barco não tem sombra total)", "Chapéu para todos", "Blusa leve para a gruta", "Sapatilha de neoprene", "Boia/colete para as crianças", "Água — muito mais do que parece necessário", "Remédio para enjoo 30 min antes de embarcar"],
  },

  {
    id: "d3",
    date: "18/08",
    weekday: "Segunda",
    title: "Blue Zone · Baunei, Golgo e Ogliastra",
    color: "#7a5cbf",
    badge: "Rota B",
    summary:
      "A Blue Zone literal. Baunei, Talana, Urzulei, Arzana e Villagrande Strisaili formam o núcleo de maior concentração de centenários já registrada no mundo. Dia longo de serra, fechado com banho no mar.",
    alerts: [
      {
        level: "warn",
        text: "Os 10 km de Baunei até o planalto do Golgo são rampa forte com curvas fechadas contínuas e trechos estreitos de mão dupla. Asfaltado e viável em carro normal, mas exige ritmo lento. Quem enjoa vai no banco da frente e toma remédio 30 min antes de sair de Orosei.",
      },
      {
        level: "warn",
        text: "Abasteça os dois carros em Orosei antes de sair. Entre Dorgali e Baunei, na SS125, praticamente não há posto — e os que existem fecham no meio do dia.",
      },
      {
        level: "info",
        text: "Com 2 carros, saiam juntos e combinem os pontos de encontro antes: no Genna Silana e no restaurante do Golgo o sinal de celular cai. Quem cansar pode descer antes sem travar o grupo.",
      },
      {
        level: "info",
        text: "No planalto do Golgo faz ~8 °C a menos que na costa e venta. Leve uma blusa para os dois de 76 anos, mesmo com 35 °C em Orosei.",
      },
    ],
    stops: [
      {
        id: "genna-silana",
        name: "Passo Genna 'e Silana",
        lat: 40.1611,
        lng: 9.5236,
        time: "10:00 · parada de 20 min",
        kind: "natureza",
        desc: "Mirante a 1.017 m na SS125, com vista de cima para o cânion de Gorropu, o mais profundo da Europa. Fica na beira da estrada, no meio do caminho para Baunei.",
        senior: "Estaciona e a vista está ali — 20 m de terreno plano. Melhor relação vista/esforço do dia inteiro. Tem bar com banheiro.",
        kids: "Cabras e porcos costumam circular soltos no estacionamento.",
        cost: "Grátis",
      },
      {
        id: "baunei-golgo",
        name: "Altopiano del Golgo",
        lat: 40.0842,
        lng: 9.6519,
        time: "11:15–13:00",
        kind: "natureza",
        desc: "Planalto a 700 m sobre Baunei, num antigo campo de lava. Igreja campestre de San Pietro, do século XVII, com as cumbessias (casinhas de romeiro) em volta. Burros, porcos, cabras e cavalos circulam soltos por todo lado.",
        senior: "Depois da subida, o planalto em si é plano e fácil. Sombra de zimbros centenários. Vale sentar e deixar o resto do grupo andar.",
        kids: "Animais soltos e mansos por toda parte. É o ponto alto do dia para as duas crianças.",
      },
      {
        id: "su-sterru",
        name: "Su Sterru — a voragem do Golgo",
        lat: 40.0806,
        lng: 9.6531,
        time: "12:00",
        kind: "natureza",
        desc: "Abismo cárstico de 270 m de profundidade — um dos mais fundos da Europa — aberto no meio do planalto. Mirante cercado na borda.",
        senior: "Do estacionamento são ~300 m de trilha em terreno de pedra irregular. Calçado fechado. Se estiver quente, é uma parada dispensável.",
        kids: "Segurar a mão das duas na borda. A grade existe, mas a queda é vertical.",
        cost: "Grátis",
      },
      {
        id: "pranzo-golgo",
        name: "Almoço pastoril no Golgo",
        lat: 40.0836,
        lng: 9.6486,
        time: "13:00–14:45",
        kind: "comida",
        desc: "É aqui que a Blue Zone deixa de ser estatística e vira almoço. Menu fixo de pastor: pane carasau, pecorino, porceddu no espeto, culurgiones, cannonau, mirto no fim. No planalto há restaurantes de cooperativa local — o mais conhecido é o Il Golgo.",
        senior: "Refeição longa, sentada e sombreada bem no miolo do calor. O descanso do dia está embutido aqui.",
        kids: "Mesas ao ar livre com os animais circulando em volta.",
        cost: "€30–40 menu fixo por adulto",
        book: true,
      },
      {
        id: "santa-maria-navarrese",
        name: "Santa Maria Navarrese",
        lat: 39.9903,
        lng: 9.6853,
        time: "15:45–18:00",
        kind: "praia",
        desc: "Descida de volta a Baunei e mais 10 min até a costa. Vila com praia de areia, torre espanhola do século XVI e uma oliveira milenar de mais de 1.000 anos ao lado da igreja.",
        senior: "Praia plana, mar calmo, sombra de pinheiros e bares na areia. Fecho de dia sem esforço nenhum.",
        kids: "Banho no fim da tarde, quando o sol já não castiga.",
      },
      {
        id: "villagrande",
        name: "Villagrande Strisaili (opcional)",
        lat: 39.9553,
        lng: 9.5136,
        time: "desvio de +1h20 ida e volta",
        kind: "vila",
        desc: "O município com a maior taxa de centenários já registrada no mundo — o marco zero dos estudos de Blue Zone. Sendo honesto: é uma vila de montanha comum, sem nada montado para turista. O valor é simbólico, não visual.",
        senior: "Não recomendo encaixar. Soma 1h20 de serra a um dia que já tem 3h de estrada, e Baunei já é Blue Zone com todos os efeitos.",
        kids: "Nada para criança.",
        optional: true,
      },
    ],
    drive: [
      { from: "Hotel", to: "Genna Silana", km: 55, min: 60, note: "SS125 Orientale Sarda. Saia 09:00." },
      { from: "Genna Silana", to: "Golgo", km: 30, min: 55, note: "Inclui os 10 km de rampa de Baunei ao planalto." },
      { from: "Santa Maria Navarrese", to: "Hotel", km: 90, min: 95, note: "Volta pela SS125. Saia da praia até 18:00 para não pegar serra no escuro." },
    ],
    pack: ["Blusa leve — o planalto é bem mais frio e ventoso que a costa", "Calçado fechado para a trilha do Su Sterru", "Remédio de enjoo antes de sair de Orosei", "Água e lanche — entre Dorgali e Baunei não há onde parar", "Roupa de banho para Santa Maria Navarrese"],
  },

  {
    id: "d4",
    date: "19/08",
    weekday: "Terça",
    title: "Cala Brandinchi + Lu Impostu",
    color: "#e0a419",
    badge: "Reserva obrigatória",
    summary:
      "A substituta de La Pelosa. Norte, 55 min de carro. Água rasa e turquesa até longe da margem — apelidada de 'Pequeno Taiti', com a ilha de Tavolara no horizonte. É a praia mais adequada do roteiro para crianças e idosos ao mesmo tempo.",
    alerts: [
      {
        level: "warn",
        text: "Cala Brandinchi tem entrada paga e cota diária limitada no verão. Reserva online obrigatória e as vagas de meados de agosto somem dias antes. Reserve assim que puder — se falhar, Lu Impostu (mesma faixa costeira, sem cota) é o plano B imediato.",
      },
      {
        level: "info",
        text: "Chegue antes das 09:30. Estacionamento enche e o calor entre 12h e 16h é pesado para os 76 anos.",
      },
    ],
    stops: [
      {
        id: "cala-brandinchi",
        name: "Cala Brandinchi",
        lat: 40.7847,
        lng: 9.6889,
        time: "09:30–13:00",
        kind: "praia",
        desc: "Areia branca finíssima, água transparente e rasa por dezenas de metros, com a ilha de Tavolara no horizonte. Pinheiral atrás da faixa de areia.",
        senior: "A melhor praia da viagem para eles: entrada na água plana e gradual, sombra de pinheiro logo atrás, estacionamento a poucos minutos a pé, quiosque e banheiro.",
        kids: "Água na cintura por muito tempo. Podem andar longe da margem com segurança.",
        cost: "~€2/pessoa entrada + estacionamento, com reserva online",
        book: true,
      },
      {
        id: "lu-impostu",
        name: "Lu Impostu",
        lat: 40.7726,
        lng: 9.688,
        time: "alternativa / tarde",
        kind: "praia",
        desc: "Colada em Cala Brandinchi, mesma água clara, mais larga e sem cota de entrada. Lagoa de flamingos atrás das dunas.",
        senior: "Mesmo perfil fácil.",
        kids: "Flamingos na lagoa de Salina Bamba.",
      },
      {
        id: "san-teodoro",
        name: "San Teodoro — almoço e passeio",
        lat: 40.7772,
        lng: 9.6714,
        time: "13:30",
        kind: "comida",
        desc: "Vila turística com bastante restaurante e sorveteria. Praia de La Cinta a 2 min, 5 km de areia.",
        senior: "Centro plano com muita sombra e banheiro fácil.",
        kids: "Sorvete e lojinhas.",
        book: true,
      },
    ],
    drive: [{ from: "Hotel", to: "Cala Brandinchi", km: 62, min: 55, note: "SS125. Saia 08:15." }],
  },

  {
    id: "d5",
    date: "20/08",
    weekday: "Quarta",
    title: "Hotel, folga e saída",
    color: "#5f8b4c",
    summary:
      "Dia de respirar. Piscina/praia do hotel de manhã, sem carro. Fecha a viagem sem ninguém exausto.",
    alerts: [
      {
        level: "info",
        text: "Confirme o horário de check-out com o hotel e peça late check-out ou um quarto de cortesia para trocar de roupa — com 8 pessoas isso muda o dia inteiro.",
      },
      {
        level: "info",
        text: "Se o voo sai de Cagliari, são 2h30 de estrada + devolução do carro. Saia com 4h30 de folga do horário do voo.",
      },
    ],
    stops: [
      {
        id: "hotel-relax",
        name: "Praia e piscina do hotel",
        lat: 40.3846,
        lng: 9.7426,
        time: "manhã",
        kind: "base",
        desc: "Zero deslocamento. Depois de 3 dias de estrada e 1 de barco, é o que o grupo precisa.",
        senior: "Sem carro, sem sol de meio-dia, sem caminhada.",
        kids: "Piscina o dia inteiro.",
      },
      {
        id: "su-barchile",
        name: "Último almoço em Orosei",
        lat: 40.3789,
        lng: 9.6963,
        time: "13:00",
        kind: "comida",
        desc: "Centro de Orosei tem boas trattorias. Feche com peixe e um cannonau.",
        book: true,
      },
    ],
    drive: [],
  },
];

const DECISION = {
  title: "La Pelosa — resolvido: trocada por Cala Brandinchi",
  resolved: true,
  lat: 40.9583,
  lng: 8.2033,
  problem:
    "Decisão tomada. La Pelosa sai do roteiro. Ficava em Stintino, extremo noroeste: 245 km e ~3h20 de Orosei em cada sentido, ou seja ~7h de carro num único dia com dois idosos de 76 anos e duas crianças. Chegar de barco também não resolvia — os passeios que saem de Stintino vão para a Asinara e passam ao largo, sem desembarcar na praia.",
  ticket:
    "No lugar dela ficam Cala Brandinchi e Lu Impostu, no dia 19/08. Entregam exatamente o que faz La Pelosa famosa — areia branca finíssima, água rasa e turquesa por dezenas de metros e uma ilha no horizonte (Tavolara no lugar de Asinara) — a 55 min do hotel em vez de 3h20. Para o perfil deste grupo é troca com ganho, não concessão.",
  options: [
    {
      label: "O que se ganha na troca",
      body: "6h30 de carro devolvidas ao grupo. Entrada na água plana e gradual em vez de praia com cota disputada a 245 km. Pinheiral com sombra logo atrás da areia. E a possibilidade de chegar cedo, sair no calor do meio-dia e voltar — coisa impossível num bate-volta a Stintino.",
      verdict: "melhor",
    },
    {
      label: "O que se perde",
      body: "A foto específica de La Pelosa com a torre aragonesa e a Asinara ao fundo, e o passeio por Alghero/Grotta di Nettuno que só faria sentido no mesmo pacote. É a única perda real — e ela custaria dois dias do Hotel Marina Garden para ser recuperada.",
      verdict: "possível",
    },
    {
      label: "Se um dia voltar à Sardenha",
      body: "La Pelosa se faz com base em Alghero ou Stintino, nunca a partir da costa leste. Reserve o acesso online com semanas de antecedência: há taxa por pessoa e cota diária de 1.500 visitantes.",
      verdict: "possível",
    },
  ],
};

const BOATS = {
  intro:
    "Sim, existem barcos bem maiores que 8 lugares saindo de Cala Gonone — e para este grupo há três formatos possíveis. O critério decisivo não é o tamanho: é ter SOMBRA e BANHEIRO A BORDO, porque são ~7h de mar com dois idosos de 76 anos.",
  options: [
    {
      name: "Motonave / battello",
      cap: "100–250 passageiros",
      price: "€45–60 por adulto · meia para as crianças",
      pros: [
        "Casco grande e pesado: quase não sente ondulação — o mais estável de todos",
        "Banheiro a bordo e convés coberto com sombra de verdade",
        "Escada de embarque larga com corrimão, não escadinha de mergulho",
        "Bar a bordo",
      ],
      cons: [
        "Horário e itinerário fixos, sem margem de negociação",
        "Cheio em agosto — chegue cedo para pegar lugar na sombra",
        "Tempo em cada cala é o do grupo todo, não o de vocês",
      ],
      verdict: "melhor",
      note: "Total estimado para os 8: ~€380–450. É a opção mais segura para os 76 anos e a mais barata ao mesmo tempo.",
    },
    {
      name: "Barco privativo com skipper (gozzo ou cabinato)",
      cap: "8–12 passageiros, exclusivo de vocês",
      price: "€900–1.500 pelo dia inteiro · ~€110–190 por pessoa",
      pros: [
        "Ritmo próprio: decidem quanto tempo ficam em cada cala e podem cortar uma parada se alguém cansar",
        "Sem disputa por sombra nem por espaço",
        "O skipper ajusta o roteiro se o mar virar — pode pular Cala Mariolu sem perder o dia",
      ],
      cons: [
        "2 a 3 vezes o preço da motonave",
        "Muitos gozzi NÃO têm banheiro a bordo — isso elimina o barco para este grupo",
        "Barco menor balança bem mais que a motonave",
      ],
      verdict: "possível",
      note: "Só vale se confirmar por escrito banheiro (WC) e toldo (tendalino). Sem os dois, escolha a motonave.",
    },
    {
      name: "Gommone",
      cap: "6–12 passageiros",
      price: "€60–120 por pessoa",
      pros: ["Chega em enseadas que barco grande não alcança", "Rápido"],
      cons: [
        "Bote inflável bate forte no mar aberto — o impacto repetido é ruim para coluna e quadril",
        "Sombra parcial ou nenhuma, sem banheiro",
        "Embarque e desembarque pela borda, sem escada fixa",
      ],
      verdict: "não",
      note: "Contraindicado com 76 anos. Não é conservadorismo: é a razão pela qual operadores costumam desaconselhar para idosos.",
    },
  ],
  ask: [
    "«C'è il WC a bordo?» — banheiro a bordo. Inegociável para 7h de mar.",
    "«C'è il tendalino / zona d'ombra?» — toldo ou área de sombra.",
    "«8 passeggeri OLTRE allo skipper?» — barcos italianos têm lotação certificada; muitos gozzi de '8 lugares' contam a tripulação junto. Vocês precisam de 8 passageiros ALÉM do skipper.",
    "«Il biglietto della Grotta del Bue Marino è incluso?» — o ingresso da gruta costuma ser à parte.",
    "«Il ticket di Cala Mariolu è incluso?» — a costa de Baunei tem cota diária paga; confirme quem compra.",
    "«Come si sale a bordo? C'è una scaletta con corrimano?» — como se embarca, e se há escada com corrimão.",
  ],
  fallback:
    "Plano de contingência com 2 carros: existe serviço de taxi boat frequente entre Cala Gonone e Cala Luna, com travessia de ~20 min. Se no dia os dois de 76 anos não estiverem bem para 7h de mar, eles fazem só Bue Marino + Cala Luna e voltam de taxi boat no início da tarde, enquanto o resto do grupo segue até Cala Mariolu. Com dois carros isso não trava ninguém.",
};

const BOOKINGS = [
  { what: "Cala Brandinchi (19/08)", when: "AGORA", why: "Cota diária + taxa de acesso. Meados de agosto esgota dias antes. Plano B sem cota: Lu Impostu, ao lado.", urgent: true },
  { what: "Barco motonave — Golfo di Orosei (17/08)", when: "com 3–4 dias", why: "Motonave, não gommone. Confirme WC a bordo, sombra e se os tickets da Grotta del Bue Marino e de Cala Mariolu estão incluídos.", urgent: true },
  { what: "Almoço no planalto do Golgo (18/08)", when: "2–3 dias antes", why: "Restaurante de cooperativa com menu fixo, mesa para 8 no alto da montanha. Sem reserva não há mesa.", urgent: true },
  { what: "Bidderosa (16/08, opcional)", when: "assim que possível", why: "~130 carros/dia. Se falhar, Cala Liberotto resolve.", urgent: false },
  { what: "Jantares em Orosei/Cala Gonone", when: "na véspera", why: "Mesa para 8 em agosto sem reserva não existe.", urgent: false },
  { what: "Late check-out no Marina Garden (20/08)", when: "no check-in", why: "8 pessoas precisam de espaço para trocar de roupa antes da estrada.", urgent: false },
  { what: "Carros — 2 unidades", when: "feito", why: "Já resolvido. Dá flexibilidade real: quem cansa volta antes sem travar o grupo.", urgent: false },
];

const GROUP_NOTES = [
  {
    icon: "76",
    title: "Os dois de 76 anos",
    items: [
      "Só dois dias passam de 1h de carro por sentido: a chegada (15/08) e a Blue Zone (18/08). O resto é curto.",
      "Os dois dias pesados são 17/08 (7h de barco) e 18/08 (3h de serra). Estão separados por perfil de esforço — mar e estrada — e cada um vem depois de uma noite inteira de descanso.",
      "Motonave e não gommone em 17/08 é o item mais importante do roteiro inteiro. Barco com WC e sombra.",
      "Calor de agosto na Sardenha bate 35 °C entre 12h e 16h. Todo bloco desse horário está na sombra, na água ou almoçando.",
      "Cala Brandinchi, Cala Liberotto, Cala Luna e Santa Maria Navarrese têm entrada plana na água. Cala Mariolu não — é seixo com fundo que cai rápido.",
      "No planalto do Golgo (18/08) faz ~8 °C a menos que na costa e venta. Blusa na mochila mesmo com 35 °C em Orosei.",
    ],
  },
  {
    icon: "7·8",
    title: "As crianças de 7 e 8",
    items: [
      "Boia ou colete em Cala Mariolu — o fundo desce muito rápido perto da margem.",
      "Sapatilha de neoprene evita 90% dos choros do dia de barco (seixo quente, ouriço, rocha).",
      "Grotta del Bue Marino e os murais de Orgosolo são as duas paradas 'culturais' que funcionam nessa idade.",
      "Remédio de enjoo antes do barco e antes das estradas de serra da Blue Zone.",
    ],
  },
  {
    icon: "2×",
    title: "Logística: 8 pessoas em 2 carros",
    items: [
      "Dois carros é a melhor configuração possível para este grupo — melhor que uma van. Quem cansa volta antes sem encerrar o dia dos outros.",
      "Monte os carros por ritmo, não por família: carro 1 com os dois de 76 anos e quem quer parar mais; carro 2 com as crianças e quem quer esticar.",
      "Combine ponto e horário de encontro ANTES de sair. Genna Silana, planalto do Golgo e a serra da SS131 DCN ficam sem sinal de celular.",
      "Nas praias com estacionamento, desembarque idosos + guarda-sóis na entrada primeiro, depois estacione.",
      "Reserve todos os restaurantes. Mesa para 8 em agosto não aparece sozinha.",
      "Leve 2 guarda-sóis próprios — aluguel para 8 pessoas fica caro rápido.",
      "Uma chave reserva de cada carro fica com outra pessoa, no outro carro.",
    ],
  },
];
