/* Dados do roteiro Sardenha 15–20/08 — 4 adultos, 2 crianças (7 e 8), 2 idosos (76) */

const BASE = { lat: 40.3846, lng: 9.7426, name: "Hotel Marina Garden — Marina di Orosei" };

const DAYS = [
  {
    id: "d0",
    date: "15/08",
    weekday: "Sexta",
    title: "Chegada · Cagliari → Orosei",
    color: "#e2725b",
    badge: "Ferragosto",
    summary:
      "Manhã em Cagliari, transfer de ~2h30 até Orosei à tarde. Dia de deslocamento — não empilhe atrações.",
    alerts: [
      {
        level: "warn",
        text: "15/08 é Ferragosto, feriado nacional. Museus, lojas e muitos restaurantes fecham ou abrem só meio período. Praias e estradas lotadas. Reserve almoço e jantar com antecedência.",
      },
      {
        level: "info",
        text: "Carro para 8 pessoas: 1 van 9 lugares ou 2 carros. Van 9 lugares em Cagliari em agosto esgota — se ainda não reservou, reserve hoje.",
      },
    ],
    stops: [
      {
        id: "cagliari-castello",
        name: "Castello + Bastione Saint Remy",
        lat: 39.2178,
        lng: 9.1145,
        time: "09:00–11:00",
        kind: "cidade",
        desc: "Bairro histórico no alto. Vista da muralha, catedral, ruelas. Terraço do Bastione é a foto da cidade.",
        senior: "Subida íngreme a pé. Use o elevador público do Bastione (Piazza Costituzione) ou os ascensori de Via Santa Croce. De carro dá pra chegar quase no topo pela Viale Buon Cammino.",
        kids: "Curto. 1h30 é o teto antes do tédio.",
        cost: "Grátis (elevadores grátis)",
      },
      {
        id: "cagliari-elefante",
        name: "Torre dell'Elefante",
        lat: 39.2192,
        lng: 9.1108,
        time: "opcional",
        kind: "cidade",
        desc: "Torre pisana de 1307. Vista aberta do alto.",
        senior: "Pular — escadas de madeira íngremes, sem elevador.",
        kids: "Gostam da subida.",
        cost: "~€3",
      },
      {
        id: "cagliari-almoco",
        name: "Almoço em Cagliari (Marina/Villanova)",
        lat: 39.2141,
        lng: 9.1156,
        time: "12:00–13:30",
        kind: "comida",
        desc: "Bairro Marina tem a maior densidade de trattorias. Peça fregola con arselle, culurgiones, malloreddus.",
        senior: "Escolha lugar com mesa interna com ar-condicionado — meio-dia de agosto em Cagliari passa de 35 °C.",
        kids: "Pizza em qualquer lugar do Marina.",
        cost: "€25–35/pessoa",
        book: true,
      },
      {
        id: "barumini",
        name: "Su Nuraxi de Barumini (parada opcional)",
        lat: 39.7053,
        lng: 8.9906,
        time: "15:00–16:30",
        kind: "cultura",
        desc: "Nuraghe UNESCO, o mais importante da ilha. Visita guiada obrigatória, ~1h. Fica ~50 min fora da rota direta.",
        senior: "Terreno irregular, sol aberto, pouca sombra. Às 15h de agosto é castigo. Se for, vá no último horário.",
        kids: "Melhor coisa 'cultural' da viagem pra idade deles — castelo de pedra de verdade.",
        cost: "€15 adulto",
        optional: true,
      },
      {
        id: "orosei-checkin",
        name: "Check-in Hotel Marina Garden",
        lat: 40.3846,
        lng: 9.7426,
        time: "17:00–18:00",
        kind: "base",
        desc: "Base para os 5 dias. Fica em Marina di Orosei, pé na areia.",
        senior: "Peça quartos no térreo ou perto do elevador na reserva.",
        kids: "Piscina antes do jantar resolve a energia acumulada da estrada.",
      },
      {
        id: "marina-orosei",
        name: "Pôr do sol na praia de Marina di Orosei",
        lat: 40.3856,
        lng: 9.744,
        time: "19:30",
        kind: "praia",
        desc: "Areia larga, dunas, pinheiral. Fim de dia sem esforço nenhum, a 3 min do hotel.",
        senior: "Acesso plano.",
        kids: "Areia solta e rasa perto da margem.",
      },
    ],
    drive: [
      { from: "Cagliari", to: "Orosei", km: 195, min: 150, note: "SS131 DCN. Via Barumini/Nuoro fica ~40 min mais longo." },
    ],
  },

  {
    id: "d1",
    date: "16/08",
    weekday: "Sábado",
    title: "Aclimatação · Orosei e praias locais",
    color: "#3fa796",
    summary:
      "Dia leve de propósito. Todo mundo chegou ontem, a semana tem 1 dia de barco e 2 de estrada. Praias a 10–20 min do hotel.",
    alerts: [
      {
        level: "info",
        text: "Bidderosa tem cota diária de carros (~130) e cobra entrada. Reserva online abre com antecedência e esgota em agosto. Se não conseguir, Cala Liberotto e Sos Alinos são vizinhas e livres.",
      },
    ],
    stops: [
      {
        id: "cala-liberotto",
        name: "Cala Liberotto",
        lat: 40.4519,
        lng: 9.781,
        time: "09:30–13:00",
        kind: "praia",
        desc: "Sequência de enseadas de areia branca com rochas graníticas, água rasa e transparente. A praia mais fácil da região.",
        senior: "Estacionamento perto, entrada plana na água, quiosques com banheiro. Melhor praia do roteiro para os 76 anos.",
        kids: "Água rasa por muitos metros e piscinas naturais entre as rochas.",
        cost: "Estacionamento pago em agosto",
      },
      {
        id: "bidderosa",
        name: "Oasi di Bidderosa (opcional, com reserva)",
        lat: 40.4302,
        lng: 9.7856,
        time: "alternativa manhã",
        kind: "praia",
        desc: "Reserva natural com 5 calas dentro de pinheiral. Número de carros limitado por dia — por isso fica vazia mesmo em agosto.",
        senior: "Entra de carro até perto das calas. Confortável.",
        kids: "Sombra de verdade no pinheiral, raro na Sardenha.",
        cost: "~€12/carro + reserva online",
        optional: true,
        book: true,
      },
      {
        id: "orosei-centro",
        name: "Centro histórico de Orosei",
        lat: 40.3789,
        lng: 9.6963,
        time: "18:00–20:00",
        kind: "cidade",
        desc: "Piazza del Popolo, San Giacomo Maggiore, ruelas de calcário. Passeggiata no fim da tarde, gelato.",
        senior: "Centro pequeno e plano. 40 min a pé cobre tudo.",
        kids: "Gelato e praça aberta.",
      },
    ],
    drive: [{ from: "Hotel", to: "Cala Liberotto", km: 12, min: 15 }],
  },

  {
    id: "d2",
    date: "17/08",
    weekday: "Domingo",
    title: "Dia de barco · Golfo di Orosei",
    color: "#2b7fd4",
    badge: "Reservar já",
    summary:
      "O dia principal. Grotta del Bue Marino + Cala Luna + Cala Mariolu de barco saindo de Cala Gonone. Único jeito prático de ver as três.",
    alerts: [
      {
        level: "warn",
        text: "Reserve motonave (barco grande, com sombra, banheiro e escada larga), NÃO gommone. Gommone é bote inflável: batida forte no mar, sem sombra, embarque acrobático. Com 76 anos é contraindicado — coluna e quadril sofrem de verdade.",
      },
      {
        level: "warn",
        text: "Reserve com 3–4 dias de antecedência no mínimo. Meados de agosto lota. Reserva se faz no porto de Cala Gonone ou online pelos consórcios locais.",
      },
      {
        level: "info",
        text: "Cala Mariolu e Cala Goloritzé têm cota diária de visitantes (costa de Baunei). Os operadores de barco normalmente já incluem o ticket — confirme na hora de reservar.",
      },
    ],
    stops: [
      {
        id: "cala-gonone-porto",
        name: "Porto de Cala Gonone — embarque",
        lat: 40.2833,
        lng: 9.6339,
        time: "08:15 no porto / saída ~09:00",
        kind: "porto",
        desc: "Chegue 45 min antes. Estacionamento no porto enche cedo — em agosto, se estiver cheio, use os estacionamentos da parte alta e desça.",
        senior: "Deixe os dois idosos e a bagagem de praia na entrada do porto antes de estacionar.",
        kids: "Banheiro antes de embarcar — no barco a fila é longa.",
        cost: "€45–60 adulto, meia para crianças (varia por roteiro)",
        book: true,
      },
      {
        id: "bue-marino",
        name: "Grotta del Bue Marino",
        lat: 40.2492,
        lng: 9.6206,
        time: "~09:30, visita 1h",
        kind: "gruta",
        desc: "Caverna marinha, última casa da foca-monge no Mediterrâneo ocidental. Visita guiada por passarela iluminada, estalactites e lago interno. ~900 m de percurso.",
        senior: "Passarela de concreto com corrimão, alguns degraus. Viável nos 76 anos em ritmo próprio. Interior é fresco (~20 °C) — leve uma blusa. Chão fica úmido/escorregadio: calçado fechado com sola, não chinelo.",
        kids: "Escuro e ecoante, com história de foca. Costuma ser o ponto alto pra criança.",
        cost: "Ticket da gruta geralmente à parte, ~€10",
      },
      {
        id: "cala-luna",
        name: "Cala Luna",
        lat: 40.2249,
        lng: 9.6232,
        time: "~11:00, parada 1h30–2h",
        kind: "praia",
        desc: "Praia larga de areia clara sob paredão calcário, com grutas abertas no fundo da enseada. A mais espaçosa do golfo.",
        senior: "A melhor parada do dia para eles: desembarque em areia, praia plana, grutas com sombra a poucos metros. Tem quiosque.",
        kids: "As grutas no fundo da praia são exploráveis a pé.",
      },
      {
        id: "cala-mariolu",
        name: "Cala Mariolu",
        lat: 40.1442,
        lng: 9.6462,
        time: "~13:30, parada 1h30",
        kind: "praia",
        desc: "Seixos brancos arredondados ('piedini') e água em degradê de turquesa. A água mais bonita do golfo.",
        senior: "Atenção: não é areia. Seixo é instável para caminhar e o fundo desce rápido. Se estiver com ondulação, considerem ficar no barco — a vista da enseada já vale.",
        kids: "Fundo cai rápido perto da margem. Boia/colete nas duas crianças.",
        cost: "Sapatilha de neoprene ajuda muito aqui — vale comprar em Cala Gonone antes.",
      },
      {
        id: "cala-gonone-volta",
        name: "Volta a Cala Gonone + jantar",
        lat: 40.2833,
        lng: 9.6339,
        time: "~17:00",
        kind: "comida",
        desc: "Jante no porto de Cala Gonone e volte a Orosei sem pressa, ou volte direto ao hotel. A estrada Cala Gonone–Dorgali é serra com curvas fechadas.",
        senior: "Depois de 8h de barco e sol, o mais provável é que queiram voltar direto. Planeje o jantar simples.",
      },
    ],
    drive: [
      { from: "Hotel", to: "Cala Gonone", km: 34, min: 40, note: "Saia 07:15. Estrada de montanha com túnel; não é rápida." },
    ],
    pack: ["Protetor solar (o barco não tem sombra total)", "Chapéu para todos", "Blusa leve para a gruta", "Sapatilha de neoprene", "Boia/colete para as crianças", "Água — muito mais do que parece necessário", "Remédio para enjoo 30 min antes de embarcar"],
  },

  {
    id: "d3",
    date: "18/08",
    weekday: "Segunda",
    title: "Blue Zone · Barbagia e Ogliastra",
    color: "#7a5cbf",
    summary:
      "Dia de interior. A Blue Zone sarda é a área montanhosa de Nuoro/Ogliastra com a maior concentração de centenários do mundo. Duas rotas possíveis — escolha uma.",
    alerts: [
      {
        level: "info",
        text: "Escolha UMA das duas rotas abaixo. Rota A é fácil e cultural. Rota B é a Blue Zone literal (Villagrande Strisaili é o município recordista) mas tem 1h a mais de serra em cada sentido.",
      },
      {
        level: "warn",
        text: "Estradas de montanha sarda: curvas fechadas contínuas. Quem enjoa deve ir no banco da frente. Abasteça antes de subir — postos são raros no interior.",
      },
    ],
    stops: [
      {
        id: "galtelli",
        name: "Galtellì — ROTA A",
        lat: 40.3903,
        lng: 9.6111,
        time: "09:30",
        kind: "vila",
        desc: "Vila medieval a 15 min de Orosei, cenário dos romances de Grazia Deledda (Nobel de Literatura 1926). Museu etnográfico a céu aberto.",
        senior: "Plano, pequeno, sombreado. Parada perfeita de aquecimento.",
        kids: "Curto.",
        route: "A",
      },
      {
        id: "oliena",
        name: "Oliena + Fonte Su Gologone — ROTA A",
        lat: 40.2669,
        lng: 9.4622,
        time: "11:00",
        kind: "natureza",
        desc: "Nascente cárstica mais forte da Sardenha, água azul-esverdeada saindo da rocha ao pé do Supramonte. Monumento natural com passarela curta.",
        senior: "Passarela curta e plana da entrada até a nascente. Sombra de plátanos. Fácil.",
        kids: "Água muito clara e peixes visíveis.",
        cost: "~€3",
        route: "A",
      },
      {
        id: "orgosolo",
        name: "Orgosolo — murais — ROTA A",
        lat: 40.202,
        lng: 9.354,
        time: "14:00",
        kind: "cultura",
        desc: "Mais de 150 murais políticos e sociais pintados nas casas desde 1969. Vila pastoril no coração da Barbagia.",
        senior: "Rua principal tem ladeira moderada; dá pra ver muita coisa estacionando no alto e descendo.",
        kids: "É uma galeria de arte ao ar livre — funciona melhor que museu.",
        route: "A",
      },
      {
        id: "pranzo-pastore",
        name: "Almoço pastoril (Orgosolo/Oliena) — ROTA A",
        lat: 40.2101,
        lng: 9.3601,
        time: "13:00",
        kind: "comida",
        desc: "É aqui que a Blue Zone deixa de ser conceito. Pane carasau, pecorino, porceddu, cannonau. Vários agriturismos fazem menu fixo com almoço ao ar livre.",
        senior: "Refeição longa, sentada, sombreada — descanso do dia embutido.",
        kids: "Muitos agriturismos têm animais soltos.",
        cost: "€30–40 menu fixo",
        book: true,
        route: "A",
      },
      {
        id: "baunei-golgo",
        name: "Altopiano del Golgo, Baunei — ROTA B",
        lat: 40.0842,
        lng: 9.6519,
        time: "11:00",
        kind: "natureza",
        desc: "Planalto a 700 m com igreja de San Pietro, o abismo Su Sterru (270 m de profundidade) e porcos, burros e cabras soltos. Restaurantes de pastor no alto.",
        senior: "A subida de Baunei ao Golgo são 10 km de curvas em rampa forte, estrada estreita. Se alguém enjoa muito, escolha a Rota A.",
        kids: "Animais soltos por toda parte. Adoram.",
        route: "B",
      },
      {
        id: "villagrande",
        name: "Villagrande Strisaili — ROTA B",
        lat: 39.9553,
        lng: 9.5136,
        time: "14:30",
        kind: "vila",
        desc: "O município com a maior taxa de centenários já registrada no mundo — o marco zero da Blue Zone sarda. Vila de montanha a 700 m, sem infraestrutura turística.",
        senior: "É uma vila real, não uma atração. O valor é o almoço e a conversa, não o roteiro.",
        kids: "Pouco pra criança. Combine com o lago Alto Flumendosa.",
        route: "B",
      },
      {
        id: "santa-maria-navarrese",
        name: "Santa Maria Navarrese — ROTA B",
        lat: 39.9903,
        lng: 9.6853,
        time: "17:00",
        kind: "praia",
        desc: "Vila costeira com praia de areia, oliveira milenar e torre espanhola. Bom fecho de dia antes de voltar.",
        senior: "Praia plana e calma, com sombra de pinheiros.",
        kids: "Banho no fim do dia.",
        route: "B",
      },
    ],
    drive: [
      { from: "Hotel", to: "Rota A (Oliena/Orgosolo)", km: 60, min: 65 },
      { from: "Hotel", to: "Rota B (Baunei/Villagrande)", km: 78, min: 85, note: "Mais 1h de serra no retorno." },
    ],
  },

  {
    id: "d4",
    date: "19/08",
    weekday: "Terça",
    title: "Cala Brandinchi + Lu Impostu",
    color: "#e0a419",
    badge: "Reserva obrigatória",
    summary:
      "Norte, 55 min de carro. Água rasa e turquesa até longe da margem — apelidada de 'Pequeno Taiti'. É a praia mais adequada do roteiro para crianças e idosos ao mesmo tempo.",
    alerts: [
      {
        level: "warn",
        text: "Cala Brandinchi tem entrada paga e cota diária limitada no verão. Reserva online obrigatória e as vagas de meados de agosto somem dias antes. Reserve assim que puder — se falhar, Lu Impostu (mesma faixa costeira, sem cota) é o plano B imediato.",
      },
      {
        level: "info",
        text: "Chegue antes das 09:30. Estacionamento enche e o calor entre 12h e 16h é pesado para os 76 anos.",
      },
    ],
    stops: [
      {
        id: "cala-brandinchi",
        name: "Cala Brandinchi",
        lat: 40.7847,
        lng: 9.6889,
        time: "09:30–13:00",
        kind: "praia",
        desc: "Areia branca finíssima, água transparente e rasa por dezenas de metros, com a ilha de Tavolara no horizonte. Pinheiral atrás da faixa de areia.",
        senior: "A melhor praia da viagem para eles: entrada na água plana e gradual, sombra de pinheiro logo atrás, estacionamento a poucos minutos a pé, quiosque e banheiro.",
        kids: "Água na cintura por muito tempo. Podem andar longe da margem com segurança.",
        cost: "~€2/pessoa entrada + estacionamento, com reserva online",
        book: true,
      },
      {
        id: "lu-impostu",
        name: "Lu Impostu",
        lat: 40.7726,
        lng: 9.688,
        time: "alternativa / tarde",
        kind: "praia",
        desc: "Colada em Cala Brandinchi, mesma água clara, mais larga e sem cota de entrada. Lagoa de flamingos atrás das dunas.",
        senior: "Mesmo perfil fácil.",
        kids: "Flamingos na lagoa de Salina Bamba.",
      },
      {
        id: "san-teodoro",
        name: "San Teodoro — almoço e passeio",
        lat: 40.7772,
        lng: 9.6714,
        time: "13:30",
        kind: "comida",
        desc: "Vila turística com bastante restaurante e sorveteria. Praia de La Cinta a 2 min, 5 km de areia.",
        senior: "Centro plano com muita sombra e banheiro fácil.",
        kids: "Sorvete e lojinhas.",
        book: true,
      },
    ],
    drive: [{ from: "Hotel", to: "Cala Brandinchi", km: 62, min: 55, note: "SS125. Saia 08:15." }],
  },

  {
    id: "d5",
    date: "20/08",
    weekday: "Quarta",
    title: "Hotel, folga e saída",
    color: "#5f8b4c",
    summary:
      "Dia de respirar. Piscina/praia do hotel de manhã, sem carro. Fecha a viagem sem ninguém exausto.",
    alerts: [
      {
        level: "info",
        text: "Confirme o horário de check-out com o hotel e peça late check-out ou um quarto de cortesia para trocar de roupa — com 8 pessoas isso muda o dia inteiro.",
      },
      {
        level: "info",
        text: "Se o voo sai de Cagliari, são 2h30 de estrada + devolução do carro. Saia com 4h30 de folga do horário do voo.",
      },
    ],
    stops: [
      {
        id: "hotel-relax",
        name: "Praia e piscina do hotel",
        lat: 40.3846,
        lng: 9.7426,
        time: "manhã",
        kind: "base",
        desc: "Zero deslocamento. Depois de 3 dias de estrada e 1 de barco, é o que o grupo precisa.",
        senior: "Sem carro, sem sol de meio-dia, sem caminhada.",
        kids: "Piscina o dia inteiro.",
      },
      {
        id: "su-barchile",
        name: "Último almoço em Orosei",
        lat: 40.3789,
        lng: 9.6963,
        time: "13:00",
        kind: "comida",
        desc: "Centro de Orosei tem boas trattorias. Feche com peixe e um cannonau.",
        book: true,
      },
    ],
    drive: [],
  },
];

const DECISION = {
  title: "La Pelosa — a decisão que precisa ser tomada antes",
  lat: 40.9583,
  lng: 8.2033,
  problem:
    "La Pelosa fica em Stintino, extremo noroeste da ilha. São 245 km e ~3h20 de Orosei em cada sentido. Bate-volta no dia = ~7h de carro, saindo às 6h e voltando à noite, com 2 idosos de 76 anos e 2 crianças. Não recomendo em nenhuma hipótese.",
  ticket:
    "A cota diária (1.500 pessoas) e a taxa de acesso valem para quem entra pela praia. Chegar de barco não é um contorno confiável — os passeios de barco que saem de Stintino vão para a Asinara e passam ao largo, sem desembarcar em La Pelosa. Contar com isso é arriscar 7h de carro para ver a praia de longe.",
  options: [
    {
      label: "Opção 1 — Trocar por Cala Brandinchi (recomendado)",
      body: "Cala Brandinchi e Lu Impostu entregam exatamente o que faz La Pelosa famosa: areia branca, água rasa e turquesa por dezenas de metros e uma ilha no horizonte (Tavolara em vez de Asinara). A 55 min do hotel em vez de 3h20. Já está no dia 19/08.",
      verdict: "melhor",
    },
    {
      label: "Opção 2 — Pernoite no noroeste (17–18/08)",
      body: "Duas noites em Alghero ou Stintino, cortando 2 dias do Hotel Marina Garden. Dá para encaixar Alghero (centro catalão), Grotta di Nettuno e La Pelosa com reserva feita com antecedência. Custo: perde o dia de barco no Golfo di Orosei OU o dia de Blue Zone, e adiciona duas mudanças de hotel com 8 pessoas.",
      verdict: "possível",
    },
    {
      label: "Opção 3 — Bate-volta de Orosei",
      body: "7h de carro em um dia de agosto, com 76 anos no banco. Chegando, ainda pode não haver ingresso.",
      verdict: "não",
    },
  ],
};

const BOOKINGS = [
  { what: "Van 9 lugares ou 2 carros em Cagliari", when: "AGORA", why: "Agosto na Sardenha esgota frota. 8 pessoas + bagagem não cabem em um carro comum.", urgent: true },
  { what: "Barco Golfo di Orosei (motonave, 17/08)", when: "com 3–4 dias", why: "Reserve motonave, não gommone. Confirme se o ticket de Cala Mariolu está incluído.", urgent: true },
  { what: "Cala Brandinchi (19/08)", when: "AGORA", why: "Cota diária + taxa de acesso. Meados de agosto esgota dias antes.", urgent: true },
  { what: "Bidderosa (16/08, opcional)", when: "assim que possível", why: "~130 carros/dia. Se falhar, Cala Liberotto resolve.", urgent: false },
  { what: "Almoço pastoril na Blue Zone (18/08)", when: "1–2 dias antes", why: "Agriturismo de menu fixo trabalha só com reserva.", urgent: false },
  { what: "Jantares em Orosei/Cala Gonone", when: "na véspera", why: "Mesa para 8 em agosto sem reserva não existe.", urgent: false },
  { what: "Late check-out no Marina Garden (20/08)", when: "no check-in", why: "8 pessoas precisam de espaço para trocar de roupa antes da estrada.", urgent: false },
];

const GROUP_NOTES = [
  {
    icon: "76",
    title: "Os dois de 76 anos",
    items: [
      "Nenhum dia tem mais de 1h25 de carro em cada sentido, exceto o dia de chegada.",
      "O único dia longo é o de barco (17/08) — e é por isso que a motonave, e não o gommone, é inegociável.",
      "Calor de agosto na Sardenha bate 35 °C entre 12h e 16h. Todo bloco desse horário do roteiro está na sombra, na água ou almoçando.",
      "Cala Brandinchi, Cala Liberotto e Cala Luna têm entrada plana na água. Cala Mariolu não — é seixo com fundo que cai rápido.",
    ],
  },
  {
    icon: "7·8",
    title: "As crianças de 7 e 8",
    items: [
      "Boia ou colete em Cala Mariolu — o fundo desce muito rápido perto da margem.",
      "Sapatilha de neoprene evita 90% dos choros do dia de barco (seixo quente, ouriço, rocha).",
      "Grotta del Bue Marino e os murais de Orgosolo são as duas paradas 'culturais' que funcionam nessa idade.",
      "Remédio de enjoo antes do barco e antes das estradas de serra da Blue Zone.",
    ],
  },
  {
    icon: "8",
    title: "Logística de grupo de 8",
    items: [
      "Reserve todos os restaurantes. Mesa para 8 em agosto não aparece sozinha.",
      "Nas praias com estacionamento, desembarque idosos + guarda-sóis primeiro, depois estacione.",
      "Dois carros dão mais flexibilidade que uma van: quem cansa volta antes.",
      "Leve 2 guarda-sóis próprios — aluguel para 8 pessoas fica caro rápido.",
    ],
  },
];
